site_name: ArrNorm
site_description: Automatic Relative Radiometric Normalization
site_author: Xavier Corredor Llano, SMBYC-IDEAM
#site_favicon: favicon_whale.png
site_url: http://smbyc.bitbucket.org/arrnorm
repo_url: https://bitbucket.org/smbyc/arrnorm
theme: readthedocs
pages:
- Home: index.md
- Test: test.md
